FROM kalilinux/kali-rolling:latest

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y \
    nmap \
    hydra \
    iputils-ping \
    curl \
    wget \
    jq 

RUN apt-get install -y \
    telnet \
    smbclient \
    redis-tools \
    python3 \
    python3-pip \
    python3-venv \
    netcat-traditional \
    metasploit-framework \
    python2.7 \
    python2.7-dev

RUN apt-get install -y \
    awscli \
    openssh-client \
    hydra \
    git \
    gcc \
    file \
    openjdk-11-jre

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /root

CMD ["/bin/bash"]
