FROM kalilinux/kali-rolling:latest

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y \
    nmap \
    hydra \
    iputils-ping \
    curl \
    wget \
    jq \
    python3 \
    python3-pip \
    python3-venv 

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /root

CMD ["/bin/bash"]
