---
- name: Install required packages
  loop: 
    - software-properties-common
    - curl
    - jq
    - iptables-persistent
    - libnetfilter-queue1
    - libnfnetlink0
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
