version: '3.8'

services:
  victim:
    build:
      context: .
      dockerfile: Dockerfile.victim
    container_name: victim
    networks:
      - warfare_network
    restart: unless-stopped

  attacker:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    container_name: attacker
    restart: unless-stopped
    networks: 
      - warfare_network
    stdin_open: true
    tty: true

networks:
  warfare_network:
    driver: bridge