version: "3.8"

networks:
  vulnnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  attacker:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    container_name: attacker
    restart: unless-stopped
    networks:
      vulnnet:
        ipv4_address: 172.20.0.10
    stdin_open: true
    tty: true

  victim-activemq:
    image: spmd/activemq:5.16.5
    container_name: victim-activemq
    hostname: victim-activemq
    networks:
      vulnnet:
        ipv4_address: 172.20.0.101
    ports:
      - "61616:61616"
      - "8161:8161"