---
- name: Copy dockerfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/{{ item }}
    owner: "{{ username }}"
    mode: "0644"
  loop: [ "Dockerfile.attacker" , "Dockerfile.victim" , "docker-compose.yaml" ]

- name: Run containers
  community.docker.docker_compose_v2:
    project_name: warfare
    project_src: /home/{{ username }}
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
